name: CI
on:
  pull_request:
    branches:
      - '*'
jobs:
  lint-typecheck-build:
    name: Lint, Type Check, and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm turbo run lint
      - name: Type check
        run: pnpm turbo run type-check
      - name: Build
        run: pnpm turbo run build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
